apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: java-api
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/toniferr/java-api-gitops.git
  ref:
    branch: main